set -g prefix C-a
bind C-a send-prefix   # C-a C-a sends a literal ^A (zsh beginning-of-line)
set -g mouse on
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on 
setw -g mode-keys vi
set -g status-position top

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'

set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# install tpm on first run
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
